In [1]:
import pandas as pd
from datetime import datetime
import pytz
import time
from io import BytesIO
import numpy as np
import os
import warnings
pd.set_option('display.max_columns', None)

In [2]:
df_datos= pd.read_csv("c:/datos/1434699_2024.csv", dtype=str)

In [3]:
df_datos.columns = (df_datos.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [5]:
df_datos['FECHA_EMISION'] = pd.to_datetime(df_datos['FECHA_EMISION'],format='%d/%m/%Y', errors='coerce').dt.date

In [6]:
df_datos.head(3)

,ANIO,PRODUCTO_RIESGO,TIPO,FECHA_EMISION,ANO,ID_CLIENTE,TIPO_DOCUMENTO,DOCUMENTO,DOCUMENTO_SUNAT,PRODUCTO,DESC_PRODUCTO,POLIZA,NUMCERT,CERT,MONEDA,N,CPTO,DESCRIP,MONTO,ESTADO_ACTUAL,ID_CONTRATANTE,NOMBRE_CONTRATANTE,TIPO_DOC_IDE,DOCIDENT_NUMERO,NUMOPER,CANAL,DES_TIPOCANAL,GLOSA,USUARIO,CODCAJERO,NUMTRAMITE,ANULADO_POR,FECHA_EMI
0,2024,BBVA,Liquidacion de Abono,2024-01-05,2024,37369763,LA,166562810,NaN,1121,SEGURO NUEVO PT BBVA,50971,NaN,1,SOL,2,IMPIVA,IMPUES,27.44,PAG,37369763,DAVID ALBENIS CORONADO CRUZ,CE,003888795,4266737612,7,NO TRADICIONAL,NaN,CORONADO CRUZ DAVID ALBENIS,NaN,NaN,DS_APIRIMAC_AX - USUARIO PORTAL API,5/01/2024
1,2024,BBVA,Liquidacion de Abono,2024-04-18,2024,8226599,LA,168912108,NaN,8014,SEGURO MULTIPLE BANCO CONTINENTAL,0110506393,0110506493,NaN,SOL,2,DEDEEM,DEREMI,2.62,PAG,8226599,JUAN CARLOS CASTILLO MARTEL,DNI,03698298,4357134077,NaN,NaN,NaN,CASTILLO MARTEL JUAN CARLOS,CGUADANC,NaN,NaN,18/04/2024
2,2024,BBVA,Liquidacion de Abono,2024-04-17,2024,405074,LA,168895784,NaN,2101,WEB VEHICULOS,1389894,NaN,76,USD,2,IMPIVA,IMPUES,14526.30,CMP,405074,INTERSENDAS S.A.C.,RUC,20419278875,4356608499,3,CORREDOR,NaN,INTERSENDAS S.A.C.,XT7351,PV877344-01,GORMENOT - Greta Ormeno Taboada,17/04/2024

In [16]:
#df_datos= pd.read_excel("c:/datos/1434675.xlsx", sheet_name=0, dtype=str)
df_datos= pd.read_excel("c:/datos/1434675.xlsx", sheet_name=0)
df_datos.columns = (df_datos.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [20]:
df_datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 265657 entries, 0 to 265656
Data columns (total 41 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IDEPOL                    96455 non-null   float64
 1   CERT_BANCO_EXCEL          265657 non-null  str
 2   NRO_CERT_BANCO            96455 non-null   str
 3   CODPROD                   96455 non-null   float64
 4   NUMPOL                    96455 non-null   float64
 5   CLIENTE                   96455 non-null   str
 6   NUMCERT                   96455 non-null   float64
 7   STSCERT                   96455 non-null   str
 8   FEC_INI_VIG_CERT          96450 non-null   str
 9   FEC_FIN_VIG_CERT          96449 non-null   str
 10  FECHA_INI_ULT_COBERTURA   96454 non-null   str
 11  FECHA_FIN_ULT_COBERTURA   96454 non-null   str
 12  CAN_LQ_COB                265657 non-null  int64
 13  CAN_LQ_INC                265657 non-null  int64
 14  CAN_LQ_ANU                265657 non-null  int64
 15  CAN_LQ_EMI                265657 non-null  int64
 16  DOCUMENTO_COB             90596 non-null   float64
 17  DOCUMENTO_ESTADO_COB      90596 non-null   str
 18  PRIMA_COB                 90596 non-null   float64
 19  FECVE_COB                 90596 non-null   str
 20  DOCUMENTO_ANU_INC         8870 non-null    float64
 21  DOCUMENTO_ESTADO_ANU_INC  8870 non-null    str
 22  PRIMA_INC_ANU             8870 non-null    float64
 23  FECVE_COB_1               8870 non-null    str
 24  P_BRUTA                   96216 non-null   float64
 25  TIPODOC                   74804 non-null   str
 26  NUMERO_LA                 74804 non-null   float64
 27  MTO_LA                    74804 non-null   float64
 28  ESTADO_LA                 74804 non-null   str
 29  CAN_LA_EMI                265657 non-null  int64
 30  NUMSIN                    2789 non-null    float64
 31  STSSIN                    2789 non-null    str
 32  FECOCURR                  2789 non-null    str
 33  MTOTOTRES                 2789 non-null    float64
 34  MTOTOTAPROB               2789 non-null    float64
 35  MTOTOTPAGADO              2789 non-null    float64
 36  MTOTOTPEND                2789 non-null    float64
 37  DESCRAMO                  2789 non-null    str
 38  TIPOVIG                   265657 non-null  str
 39  CODMONEDA                 96455 non-null   str
 40  CALCULO_PRIMA             265657 non-null  str
dtypes: float64(16), int64(5), str(20)
memory usage: 83.1 MB

In [23]:
#df_datos2= pd.read_excel("c:/datos/1434628.xlsx", sheet_name=0, dtype=str)
df_datos2= pd.read_excel("c:/datos/1434628.xlsx", sheet_name=0)
df_datos2.columns = (df_datos2.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [25]:
df_datos2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3343 entries, 0 to 3342
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   IDEPOL                    3096 non-null   float64
 1   CERT_BANCO_EXCEL          3343 non-null   int64
 2   NRO_CERT_BANCO            3096 non-null   str
 3   TIPO_SEGURO               0 non-null      float64
 4   CODPROD                   3096 non-null   float64
 5   NUMPOL                    3096 non-null   float64
 6   CLIENTE                   3096 non-null   str
 7   NUMCERT                   3096 non-null   float64
 8   STSCERT                   3096 non-null   str
 9   FEC_INI_VIG_CERT          3096 non-null   datetime64[us]
 10  FEC_FIN_VIG_CERT          3096 non-null   datetime64[us]
 11  FECHA_INI_ULT_COBERTURA   3096 non-null   datetime64[us]
 12  FECHA_FIN_ULT_COBERTURA   3096 non-null   datetime64[us]
 13  CAN_LQ_COB                3343 non-null   int64
 14  CAN_LQ_INC                3343 non-null   int64
 15  CAN_LQ_ANU                3343 non-null   int64
 16  CAN_LQ_EMI                3343 non-null   int64
 17  DOCUMENTO_COB             2479 non-null   float64
 18  DOCUMENTO_ESTADO_COB      2479 non-null   str
 19  PRIMA_COB                 2479 non-null   float64
 20  FECVE_COB                 2479 non-null   datetime64[us]
 21  DOCUMENTO_ANU_INC         688 non-null    float64
 22  DOCUMENTO_ESTADO_ANU_INC  688 non-null    str
 23  PRIMA_INC_ANU             688 non-null    float64
 24  FECVE_COB_1               688 non-null    datetime64[us]
 25  P_BRUTA                   3085 non-null   float64
 26  TIPODOC                   1165 non-null   str
 27  NUMERO_LA                 1165 non-null   float64
 28  MTO_LA                    1165 non-null   float64
 29  ESTADO_LA                 1165 non-null   str
 30  CAN_LA_EMI                3343 non-null   int64
 31  NUMSIN                    133 non-null    float64
 32  STSSIN                    133 non-null    str
 33  FECOCURR                  133 non-null    datetime64[us]
 34  MTOTOTRES                 133 non-null    float64
 35  MTOTOTAPROB               133 non-null    float64
 36  MTOTOTPAGADO              133 non-null    float64
 37  MTOTOTPEND                133 non-null    float64
 38  DESCRAMO                  133 non-null    str
 39  TIPOVIG                   3343 non-null   str
 40  CODMONEDA                 3096 non-null   str
 41  CALCULO_PRIMA             3343 non-null   str
dtypes: datetime64[us](7), float64(17), int64(6), str(12)
memory usage: 1.1 MB

In [9]:
df_datos= df_datos.rename(columns={'NRO_CERT_BANCO':'CERTIFICADO_BANCO', 'TIPO_SEGURO':'PRODUCTO',
                                'FEC_INI_VIG_CERT':'FECHA_INICIO_VIGENCIA', 'FEC_FIN_VIG_CERT':'FECHA_FIN_VIGENCIA',
                                'FECVE_COB':'FECHA_VE_COB', 'FECVE_COB_1':'FECHA_VE_INCANU','FECOCURR':'FECHA_OCURR',
                                'DOCUMENTO_COB':'DOC_COB', 'DOCUMENTO_ESTADO_COB':'DOC_ESTADO_COB',
                                'DOCUMENTO_ANU_INC':'DOC_ANU_INC','DOCUMENTO_ESTADO_ANU_INC':'DOC_ESTADO_ANU_INC',
                                'P_BRUTA':'PRIMA_BRUTA','MTO_LA':'MONTO_LA'})

In [ ]:
df_datos['FECHA_INICIO_VIGENCIA'] = pd.to_datetime(df_datos['FECHA_INICIO_VIGENCIA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_FIN_VIGENCIA'] = pd.to_datetime(df_datos['FECHA_FIN_VIGENCIA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_INI_ULT_COBERTURA'] = pd.to_datetime(df_datos['FECHA_INI_ULT_COBERTURA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_FIN_ULT_COBERTURA'] = pd.to_datetime(df_datos['FECHA_FIN_ULT_COBERTURA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_VE_COB'] = pd.to_datetime(df_datos['FECHA_VE_COB'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_VE_INCANU'] = pd.to_datetime(df_datos['FECHA_VE_INCANU'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_OCURR'] = pd.to_datetime(df_datos['FECHA_OCURR'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['CAN_LQ_COB'] = pd.to_numeric(df_datos['CAN_LQ_COB'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_INC'] = pd.to_numeric(df_datos['CAN_LQ_INC'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_ANU'] = pd.to_numeric(df_datos['CAN_LQ_ANU'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_EMI'] = pd.to_numeric(df_datos['CAN_LQ_EMI'], errors='coerce').astype('Int64')
df_datos['PRIMA_COB'] = pd.to_numeric(df_datos['PRIMA_COB'], errors="coerce").astype('float64')
df_datos['PRIMA_INC_ANU'] = pd.to_numeric(df_datos['PRIMA_INC_ANU'], errors="coerce").astype('float64')
df_datos['PRIMA_BRUTA'] = pd.to_numeric(df_datos['PRIMA_BRUTA'], errors="coerce").astype('float64')
df_datos['MONTO_LA'] = pd.to_numeric(df_datos['MONTO_LA'], errors="coerce").astype('float64')
df_datos['MTOTOTRES'] = pd.to_numeric(df_datos['MTOTOTRES'], errors="coerce").astype('float64')
df_datos['MTOTOTAPROB'] = pd.to_numeric(df_datos['MTOTOTAPROB'], errors="coerce").astype('float64')
df_datos['MTOTOTPAGADO'] = pd.to_numeric(df_datos['MTOTOTPAGADO'], errors="coerce").astype('float64')
df_datos['MTOTOTPEND'] = pd.to_numeric(df_datos['MTOTOTPEND'], errors="coerce").astype('float64')

df_datos['FECHA_INI_ULT_COBERTURA'] = df_datos.apply(lambda r: restar_fecha(r['FECHA_FIN_ULT_COBERTURA'], r['CALCULO_PRIMA']), axis=1)

In [11]:
df_datos.head(3)

,IDEPOL,CERT_BANCO_EXCEL,CERTIFICADO_BANCO,CODPROD,NUMPOL,CLIENTE,NUMCERT,STSCERT,FECHA_INICIO_VIGENCIA,FECHA_FIN_VIGENCIA,FECHA_INI_ULT_COBERTURA,FECHA_FIN_ULT_COBERTURA,CAN_LQ_COB,CAN_LQ_INC,CAN_LQ_ANU,CAN_LQ_EMI,DOC_COB,DOC_ESTADO_COB,PRIMA_COB,FECHA_VE_COB,DOC_ANU_INC,DOC_ESTADO_ANU_INC,PRIMA_INC_ANU,FECHA_VE_INCANU,PRIMA_BRUTA,TIPODOC,NUMERO_LA,MONTO_LA,ESTADO_LA,CAN_LA_EMI,NUMSIN,STSSIN,FECHA_OCURR,MTOTOTRES,MTOTOTAPROB,MTOTOTPAGADO,MTOTOTPEND,DESCRAMO,TIPOVIG,CODMONEDA,CALCULO_PRIMA
0,12566562,00119999594000271325,00119999594000271325,1103,500093,VILMA JIMENEZ JIMENEZ,109846,ANU,4/10/2021,22/05/2065,16/10/2024,4/10/2025,4,0,0,4,904952527,COB,41,25/11/2021,NaN,NaN,NaN,NaN,33.73,LA,176259245,39.98,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL
1,12566562,00119999584000249052,00119999584000249052,1103,500093,OSCAR CIEZA HEREDIA,109838,ANU,6/05/2021,31/01/2057,29/11/2025,6/05/2026,5,0,0,5,904951030,COB,41,25/11/2021,NaN,NaN,NaN,NaN,33.73,LA,178358985,17.81,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL
2,11995329,00119999574000267980,00119999574000267980,1103,500091,RAFAEL DIAZ JULIAN,9981,ANU,3/09/2020,1/06/2040,6/05/2026,3/09/2026,6,0,0,6,825590690,COB,41,10/11/2020,NaN,NaN,NaN,NaN,33.73,LA,179637360,13.56,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL

In [15]:
df_datos2.tail(3)

,IDEPOL,CERT_BANCO_EXCEL,NRO_CERT_BANCO,TIPO_SEGURO,CODPROD,NUMPOL,CLIENTE,NUMCERT,STSCERT,FEC_INI_VIG_CERT,FEC_FIN_VIG_CERT,FECHA_INI_ULT_COBERTURA,FECHA_FIN_ULT_COBERTURA,CAN_LQ_COB,CAN_LQ_INC,CAN_LQ_ANU,CAN_LQ_EMI,DOCUMENTO_COB,DOCUMENTO_ESTADO_COB,PRIMA_COB,FECVE_COB,DOCUMENTO_ANU_INC,DOCUMENTO_ESTADO_ANU_INC,PRIMA_INC_ANU,FECVE_COB_1,P_BRUTA,TIPODOC,NUMERO_LA,MTO_LA,ESTADO_LA,CAN_LA_EMI,NUMSIN,STSSIN,FECOCURR,MTOTOTRES,MTOTOTAPROB,MTOTOTPAGADO,MTOTOTPEND,DESCRAMO,TIPOVIG,CODMONEDA,CALCULO_PRIMA
3340,1628856091,00110163334000433929,00110163334000433929,NaN,1121,256392,ERNESTO FLORES VENTURA,1,ANU,2025-03-15 00:00:00,2026-03-15 00:00:00,2026-01-21 00:00:00,2026-03-15 00:00:00,1,0,0,1,1163634749,COB,179.01,2025-03-15 00:00:00,NaN,NaN,NaN,NaN,147.28,LA,179407314,25.92,PAG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL
3341,1628858647,00110348024000531497,00110348024000531497,NaN,1121,107391,PAUL DAVE ROMERO CANARIO,1,REN,2025-04-30 00:00:00,2026-04-30 00:00:00,2025-04-30 00:00:00,2026-04-30 00:00:00,1,0,0,1,1163644968,COB,179.89,2025-04-30 00:00:00,NaN,NaN,NaN,NaN,148.01,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL
3342,1628494378,00110659014000253250,00110659014000253250,NaN,1121,72335,MABEL LIDANA MAGUIÑA DIAZ,1,REN,2025-02-12 00:00:00,2026-02-12 00:00:00,2025-02-12 00:00:00,2026-02-12 00:00:00,1,0,0,1,1161485876,COB,179.89,2025-02-12 00:00:00,NaN,NaN,NaN,NaN,148.01,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL

In [12]:
df_datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 265657 entries, 0 to 265656
Data columns (total 41 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   IDEPOL                   96455 non-null   str
 1   CERT_BANCO_EXCEL         265657 non-null  str
 2   CERTIFICADO_BANCO        96455 non-null   str
 3   CODPROD                  96455 non-null   str
 4   NUMPOL                   96455 non-null   str
 5   CLIENTE                  96455 non-null   str
 6   NUMCERT                  96455 non-null   str
 7   STSCERT                  96455 non-null   str
 8   FECHA_INICIO_VIGENCIA    96450 non-null   str
 9   FECHA_FIN_VIGENCIA       96449 non-null   str
 10  FECHA_INI_ULT_COBERTURA  96454 non-null   str
 11  FECHA_FIN_ULT_COBERTURA  96454 non-null   str
 12  CAN_LQ_COB               265657 non-null  str
 13  CAN_LQ_INC               265657 non-null  str
 14  CAN_LQ_ANU               265657 non-null  str
 15  CAN_LQ_EMI               265657 non-null  str
 16  DOC_COB                  90596 non-null   str
 17  DOC_ESTADO_COB           90596 non-null   str
 18  PRIMA_COB                90596 non-null   str
 19  FECHA_VE_COB             90596 non-null   str
 20  DOC_ANU_INC              8870 non-null    str
 21  DOC_ESTADO_ANU_INC       8870 non-null    str
 22  PRIMA_INC_ANU            8870 non-null    str
 23  FECHA_VE_INCANU          8870 non-null    str
 24  PRIMA_BRUTA              96216 non-null   str
 25  TIPODOC                  74804 non-null   str
 26  NUMERO_LA                74804 non-null   str
 27  MONTO_LA                 74804 non-null   str
 28  ESTADO_LA                74804 non-null   str
 29  CAN_LA_EMI               265657 non-null  str
 30  NUMSIN                   2789 non-null    str
 31  STSSIN                   2789 non-null    str
 32  FECHA_OCURR              2789 non-null    str
 33  MTOTOTRES                2789 non-null    str
 34  MTOTOTAPROB              2789 non-null    str
 35  MTOTOTPAGADO             2789 non-null    str
 36  MTOTOTPEND               2789 non-null    str
 37  DESCRAMO                 2789 non-null    str
 38  TIPOVIG                  265657 non-null  str
 39  CODMONEDA                96455 non-null   str
 40  CALCULO_PRIMA            265657 non-null  str
dtypes: str(41)
memory usage: 83.1 MB

## MATRIZ DE ERRORES

In [14]:
df_matriz_errores= pd.read_excel("c:/datos/Matriz de errores.xlsx", sheet_name='MATRIZ', dtype=str)
df_matriz_errores['IDE_ERROR'] = df_matriz_errores['IDE_ERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else np.nan)

In [15]:
df_matriz_errores.head(3)

,IDE_ENTIDAD,NOM_ENTIDAD,STS_ESTADO,IDE_CONCEPTO,DESC_CONCEPTO,IDE_GRPVAL,NOM_GRPVAL,IDE_ESCENARIO,ESTADO,IDE_ARCH_CAMPOVAL,ID_POPERADOR,CAD_VALORRES,NOM_CAMPO_VAL,DESC_CAMPOVAL,IDE_ARCHCAMPO,COD_CONTROL,NOM_CAMPO,DESC_CAMPO,IDE_VALIDACION,NOM_VALIDACION,DESC_VALIDACION,CATEGORIA_GRUPO,IDE_REGLA,NOM_REGLA,DESC_REGLA,CAD_REGLA,IDE_ERROR,COD_ERROR,NOM_ERROR,CAD_IMPRESION,IDP_RESPONSABLE
0,634,Interfaz AMC REGULAR WEB EMPRESAS,1,590,Cpto AMC COLECTIVA REGULAR WEB EMPRESAS,1089,Grupo de Validacion EPS - CP,9,ACT,24700,=,'***',NaN,NaN,3898,TER00031,INDSEXO,Sexo,459,VAL - Valores Nulos mejorado,Valores Nulos mejorado,VALOR NULO O VACIO,126,"Error, valores igual null mejorado","Error, valores igual null mejorado","select nvl(trim(<VALOR>),'***') from dual",0014,0011,EL VALOR ENVIADO ES NULO,EL CAMPO mx1 NO DEBE SER VACIO NI TENER ESPACI...,EXT
1,198,Interfaz EPS - REHDER,1,272,Cpto para producto EPS - REHDER,142,Grupo de Validacion EPS - Exc,11,ACT,1134,<>,1,EPS - Codigo Motivo Exclusion No configurado,EPS - Codigo Motivo Exclusion No configurado,3823,ACU00002,CODMOTIVOEXC,Codigo Motivo Baja - Exclusion,12,VAL - No existe config. Cod. Motivo de Exlusión,Validar - Configuración del Código de Motivo d...,ERRORES DE CONFIGURACION,430,Regla - Codigo de Motivo de Exclusion,Regla - Codigo de Motivo de Exclusion,select count(1)_x000D_\n from app_iaa...,0036,0023,"No existe configurado, Código motivo exclusión","EL CAMPO mx1 NO ES VALIDO, EN LA TRAMA DICE [m...",EXT
2,198,Interfaz EPS - REHDER,1,272,Cpto para producto EPS - REHDER,142,Grupo de Validacion EPS - Exc,11,ACT,1144,<>,1,EPS - Tipo Movimiento Incorrecto,EPS - Tipo Movimiento Incorrecto,3803,TRA00003,IDEESCENARIO,Tipo Movimiento,11,VAL - No existe configurado Tipo Movimiento,VAL - No existe configurado Tipo Movimiento,ERRORES DE CONFIGURACION,429,Regla - Configurar Tipo Movimiento,Regla - Configurar Tipo Movimiento,select count(1) from int_escenario where idees...,0031,0077,"No existe configurado, tipo movimiento: mx2","EL CAMPO mx1 NO ES VALIDO, EN LA TRAMA DICE [m...",EXT

In [16]:
df_matriz_errores.info()

<class 'pandas.DataFrame'>
RangeIndex: 620 entries, 0 to 619
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   IDE_ENTIDAD        620 non-null    str
 1   NOM_ENTIDAD        620 non-null    str
 2   STS_ESTADO         620 non-null    str
 3   IDE_CONCEPTO       620 non-null    str
 4   DESC_CONCEPTO      620 non-null    str
 5   IDE_GRPVAL         620 non-null    str
 6   NOM_GRPVAL         620 non-null    str
 7   IDE_ESCENARIO      617 non-null    str
 8   ESTADO             620 non-null    str
 9   IDE_ARCH_CAMPOVAL  620 non-null    str
 10  ID_POPERADOR       620 non-null    str
 11  CAD_VALORRES       589 non-null    str
 12  NOM_CAMPO_VAL      132 non-null    str
 13  DESC_CAMPOVAL      192 non-null    str
 14  IDE_ARCHCAMPO      620 non-null    str
 15  COD_CONTROL        620 non-null    str
 16  NOM_CAMPO          620 non-null    str
 17  DESC_CAMPO         620 non-null    str
 18  IDE_VALIDACION     620 non-null    str
 19  NOM_VALIDACION     620 non-null    str
 20  DESC_VALIDACION    582 non-null    str
 21  CATEGORIA_GRUPO    590 non-null    str
 22  IDE_REGLA          620 non-null    str
 23  NOM_REGLA          620 non-null    str
 24  DESC_REGLA         572 non-null    str
 25  CAD_REGLA          620 non-null    str
 26  IDE_ERROR          620 non-null    str
 27  COD_ERROR          620 non-null    str
 28  NOM_ERROR          620 non-null    str
 29  CAD_IMPRESION      619 non-null    str
 30  IDP_RESPONSABLE    620 non-null    str
dtypes: str(31)
memory usage: 150.3 KB

## DICCIONARIO DE VARIABLES

In [17]:
df_diccionario= pd.read_excel("c:/datos/Diccionario.xlsx", sheet_name=0, dtype=str)

In [18]:
df_diccionario.head(3)

,TIPO,VARIABLES,DEFINICION
0,Funciones,pq_iaa_intemision.fn_gps_auto_so,Determina si un vehículo requiere GPS según su...
1,Funciones,pq_iaa_intemision.fn_val_indinspeccion,Determina si se debe realizar una inspección p...
2,Funciones,pq_iaa_intequivalencia.fn_obt_valorxequivalenc...,Obtiene el valor equivalente para un dato segú...

In [2]:
def limpiar_fecha(columna):
    col = columna.astype(str) # Convertir a string
    col = col.str.strip()  # Eliminar espacios
    # Quitar decimales tipo '19880329.0'
    col = col.str.replace(r"\.0$", "", regex=True)
    col = col.str[:8] # Mantener solo los 8 primeros caracteres
    # Reemplazar valores inválidos (que no tengan 8 dígitos) por NaN
    col = col.where(col.str.match(r"^\d{8}$"), np.nan)
    return pd.to_datetime(col, format="%Y%m%d", errors="coerce").dt.date  # Convertir a fecha

def extraer_fecha(fecha):
    try:
        fecha_str = fecha.split("_")[2]
        return datetime.strptime(fecha_str, "%Y%m%d").date()
    except Exception:
        return None  # En caso de error

## REPORTE DE ERRORES

In [3]:
df_errores= pd.read_csv("C:/datos/LOTE_446.csv", dtype=str, sep= ';',encoding= 'latin-1', engine='python')
df_errores.columns = df_errores.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True)

In [4]:
df_errores.head(3)

,NRO_LOTE,LOTES_ANTERIORES,FECHA_CARGA,CODIGO_PRODUCTO,PRODUCTO,CODIGO_PLAN,NOMBRE_DE_PLAN,COD_DE_CERTIFICADO,FECINI_ALTA_CERTIFICADO,FECFIN_ALTA_CERTIFICADO,IDEDET,TIPO_MOVIMIENTO,FEC__INICIO,FEC__FIN,MONEDA,SUMA_ASEGURADA,TASA,TASA_RECARGO,PRIMABRUTACAN,PRIMANETACAN,NOMCOMPLETO,APEPATERNO,APEMATERNO,FECNACIMIENTO,TIPDOCUMENTO,NUMDOCUMENTO,NOMBRE_DE_ARCHIVO,LINEA_TRAMA,IDELOTE,IDEDET_1,ORIGEN_ERROR,CODIGO_ERROR,DESCRIPCION_ERROR
0,52337,NaN,3/12/2015 14:08:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98768069,Sin Movimiento,04/09/2012,26/10/2037,USD,250000,0.52,"0,52",130,126.21,AUGUSTO PEDRO,PROA#O,VARGAS,19720812,2,07264871,20100130204_0157001_20151203_003.TXT,903001101062640000323030011010629960005301201U...,52337,98768069,Error canal,983,"ERROR, No puede haber más de dos registros aso..."
1,52337,NaN,3/12/2015 14:08:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98768096,Sin Movimiento,29/05/2014,01/02/2027,SOL,364000,0.52,"0,52",101.92,98.95,FANNY GUISSELLA,ROJAS,CABANILLAS,19861203,2,44031374,20100130204_0157001_20151203_003.TXT,903001101179440002959320011011790960027431001P...,52337,98768096,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."
2,52337,NaN,3/12/2015 14:08:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,98768179,Sin Movimiento,28/09/2011,17/09/2031,SOL,526400,0.52,"125,52",331.63,321.97,DACY FELICITAS,ESPINOZA,CASTRO VDA DE CASTEL,19571031,2,09071165,20100130204_0157001_20151203_003.TXT,903001101526940001067740011015268960016693401P...,52337,98768179,Error canal,983,"ERROR, Al ser tipo de titular mancomuno debe h..."

In [5]:
df_errores.drop(['IDELOTE','IDEDET_1'], axis=1, inplace=True)
df_errores= df_errores.rename(columns={'DESCRIPCION_ERROR':'DESCRIPCION_ERROR_SAS', 'CODIGO_ERROR':'IDEERROR'})

In [6]:
df_errores["MONEDA"] = df_errores["MONEDA"].replace(r"^\s*$", None, regex=True)
df_errores["MONEDA"] = df_errores["MONEDA"].where(df_errores["MONEDA"].isin(["USD", "SOL"]), "SIN DATO")
df_errores= df_errores.fillna({'LOTES_ANTERIORES':'', 'ORIGEN_ERROR': 'SIN DATO', 'TIPDOCUMENTO':'SIN DATO'})
df_errores.loc[df_errores['ORIGEN_ERROR'] == 'nan', 'ORIGEN_ERROR'] = 'SIN DATO'

In [7]:
df_errores['SUMA_ASEGURADA'] = df_errores['SUMA_ASEGURADA'].str.replace(',', '.', regex=False)
df_errores['TASA'] = df_errores['TASA'].str.replace(',', '.', regex=False)
df_errores['TASA_RECARGO'] = df_errores['TASA_RECARGO'].str.replace(',', '.', regex=False)
df_errores['PRIMABRUTACAN'] = df_errores['PRIMABRUTACAN'].str.replace(',', '.', regex=False)
df_errores['PRIMANETACAN'] = df_errores['PRIMANETACAN'].str.replace(',', '.', regex=False)

In [8]:
df_errores["LOTES_ANTERIORES"] = df_errores["LOTES_ANTERIORES"].astype(str)
df_errores['FECHA_CARGA'] = pd.to_datetime(df_errores['FECHA_CARGA'], format="%d/%m/%Y %H:%M:%S", errors='coerce').dt.date
df_errores['CODIGO_PRODUCTO'] = df_errores['CODIGO_PRODUCTO'].fillna(0).astype('int')
df_errores["PRODUCTO"] = df_errores["PRODUCTO"].astype(str)
df_errores['CODIGO_PLAN'] = df_errores['CODIGO_PLAN'].fillna(0).astype('int')
#df_errores["NOMBRE_DE_PLAN"] = df_errores["NOMBRE_DE_PLAN"].astype(str)
df_errores["COD_DE_CERTIFICADO"] = df_errores["COD_DE_CERTIFICADO"].astype(str)
df_errores['FECINI_ALTA_CERTIFICADO'] = pd.to_datetime(df_errores['FECINI_ALTA_CERTIFICADO'], format='%d/%m/%Y', errors='coerce').dt.date
df_errores['FECFIN_ALTA_CERTIFICADO'] = pd.to_datetime(df_errores['FECFIN_ALTA_CERTIFICADO'], format='%d/%m/%Y', errors='coerce').dt.date
df_errores["TIPO_MOVIMIENTO"] = df_errores["TIPO_MOVIMIENTO"].astype(str)
df_errores['FEC__INICIO'] = pd.to_datetime(df_errores['FEC__INICIO'], format='%d/%m/%Y', errors='coerce').dt.date
df_errores['FEC__FIN'] = pd.to_datetime(df_errores['FEC__FIN'], format='%d/%m/%Y', errors='coerce').dt.date
df_errores['MONEDA'] = df_errores['MONEDA'].astype(str)
df_errores['SUMA_ASEGURADA'] = pd.to_numeric(df_errores['SUMA_ASEGURADA'], errors="coerce").astype('float64')
df_errores['TASA'] = pd.to_numeric(df_errores['TASA'], errors="coerce").astype('float64')
df_errores['TASA_RECARGO'] = pd.to_numeric(df_errores['TASA_RECARGO'], errors="coerce").astype('float64')
df_errores['PRIMABRUTACAN'] = pd.to_numeric(df_errores['PRIMABRUTACAN'], errors="coerce").astype('float64')
df_errores['PRIMANETACAN'] = pd.to_numeric(df_errores['PRIMANETACAN'], errors="coerce").astype('float64')
df_errores['NOMCOMPLETO'] = df_errores['NOMCOMPLETO'].astype(str)
df_errores['APEPATERNO'] = df_errores['APEPATERNO'].astype(str)
df_errores['APEMATERNO'] = df_errores['APEMATERNO'].astype(str)
df_errores["FECNACIMIENTO"] = limpiar_fecha(df_errores["FECNACIMIENTO"])
df_errores["TIPDOCUMENTO"] = df_errores["TIPDOCUMENTO"].astype(str)
df_errores['NUMDOCUMENTO'] = df_errores['NUMDOCUMENTO'].astype(str)
df_errores['NOMBRE_DE_ARCHIVO'] = df_errores['NOMBRE_DE_ARCHIVO'].astype(str)
df_errores['LINEA_TRAMA'] = df_errores['LINEA_TRAMA'].astype(str)
df_errores['ORIGEN_ERROR'] = df_errores['ORIGEN_ERROR'].astype(str)
df_errores['IDEERROR'] = df_errores['IDEERROR'].apply(lambda x: str(int(x)).zfill(4) if pd.notnull(x) else "")

In [9]:
df_errores= df_errores[df_errores['PRIMABRUTACAN']<30000]

In [10]:
df_errores['FECHA_TRAMA'] = df_errores['NOMBRE_DE_ARCHIVO'].apply(extraer_fecha)
df_errores['FECHA_TRAMA']= pd.to_datetime(df_errores['FECHA_TRAMA'], errors='coerce').dt.date

In [11]:
df_errores["TIPO_SEGURO"] = df_errores["LINEA_TRAMA"].str[:3]
df_errores["TIPO_MOVIMIENTO_NUM"] = df_errores["LINEA_TRAMA"].str[48]
df_errores["TIPO_REGISTRO"] = df_errores["LINEA_TRAMA"].str[43:45]

In [13]:
df_errores.info()

<class 'pandas.DataFrame'>
Index: 1810072 entries, 0 to 1813837
Data columns (total 35 columns):
 #   Column                   Dtype
---  ------                   -----
 0   NRO_LOTE                 str
 1   LOTES_ANTERIORES         str
 2   FECHA_CARGA              object
 3   CODIGO_PRODUCTO          int64
 4   PRODUCTO                 str
 5   CODIGO_PLAN              int64
 6   NOMBRE_DE_PLAN           str
 7   COD_DE_CERTIFICADO       str
 8   FECINI_ALTA_CERTIFICADO  object
 9   FECFIN_ALTA_CERTIFICADO  object
 10  IDEDET                   str
 11  TIPO_MOVIMIENTO          str
 12  FEC__INICIO              object
 13  FEC__FIN                 object
 14  MONEDA                   str
 15  SUMA_ASEGURADA           float64
 16  TASA                     float64
 17  TASA_RECARGO             float64
 18  PRIMABRUTACAN            float64
 19  PRIMANETACAN             float64
 20  NOMCOMPLETO              str
 21  APEPATERNO               str
 22  APEMATERNO               str
 23  FECNACIMIENTO            object
 24  TIPDOCUMENTO             str
 25  NUMDOCUMENTO             str
 26  NOMBRE_DE_ARCHIVO        str
 27  LINEA_TRAMA              str
 28  ORIGEN_ERROR             str
 29  IDEERROR                 str
 30  DESCRIPCION_ERROR_SAS    str
 31  FECHA_TRAMA              object
 32  TIPO_SEGURO              str
 33  TIPO_MOVIMIENTO_NUM      str
 34  TIPO_REGISTRO            str
dtypes: float64(5), int64(2), object(7), str(21)
memory usage: 497.2+ MB