In [6]:
import pandas as pd
from datetime import datetime
import pytz
import time
from io import BytesIO
import numpy as np
import os
import warnings
pd.set_option('display.max_columns', None)

In [16]:
#df_datos= pd.read_excel("c:/datos/1434675.xlsx", sheet_name=0, dtype=str)
df_datos= pd.read_excel("c:/datos/1434675.xlsx", sheet_name=0)
df_datos.columns = (df_datos.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [20]:
df_datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 265657 entries, 0 to 265656
Data columns (total 41 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   IDEPOL                    96455 non-null   float64
 1   CERT_BANCO_EXCEL          265657 non-null  str
 2   NRO_CERT_BANCO            96455 non-null   str
 3   CODPROD                   96455 non-null   float64
 4   NUMPOL                    96455 non-null   float64
 5   CLIENTE                   96455 non-null   str
 6   NUMCERT                   96455 non-null   float64
 7   STSCERT                   96455 non-null   str
 8   FEC_INI_VIG_CERT          96450 non-null   str
 9   FEC_FIN_VIG_CERT          96449 non-null   str
 10  FECHA_INI_ULT_COBERTURA   96454 non-null   str
 11  FECHA_FIN_ULT_COBERTURA   96454 non-null   str
 12  CAN_LQ_COB                265657 non-null  int64
 13  CAN_LQ_INC                265657 non-null  int64
 14  CAN_LQ_ANU                265657 non-null  int64
 15  CAN_LQ_EMI                265657 non-null  int64
 16  DOCUMENTO_COB             90596 non-null   float64
 17  DOCUMENTO_ESTADO_COB      90596 non-null   str
 18  PRIMA_COB                 90596 non-null   float64
 19  FECVE_COB                 90596 non-null   str
 20  DOCUMENTO_ANU_INC         8870 non-null    float64
 21  DOCUMENTO_ESTADO_ANU_INC  8870 non-null    str
 22  PRIMA_INC_ANU             8870 non-null    float64
 23  FECVE_COB_1               8870 non-null    str
 24  P_BRUTA                   96216 non-null   float64
 25  TIPODOC                   74804 non-null   str
 26  NUMERO_LA                 74804 non-null   float64
 27  MTO_LA                    74804 non-null   float64
 28  ESTADO_LA                 74804 non-null   str
 29  CAN_LA_EMI                265657 non-null  int64
 30  NUMSIN                    2789 non-null    float64
 31  STSSIN                    2789 non-null    str
 32  FECOCURR                  2789 non-null    str
 33  MTOTOTRES                 2789 non-null    float64
 34  MTOTOTAPROB               2789 non-null    float64
 35  MTOTOTPAGADO              2789 non-null    float64
 36  MTOTOTPEND                2789 non-null    float64
 37  DESCRAMO                  2789 non-null    str
 38  TIPOVIG                   265657 non-null  str
 39  CODMONEDA                 96455 non-null   str
 40  CALCULO_PRIMA             265657 non-null  str
dtypes: float64(16), int64(5), str(20)
memory usage: 83.1 MB

In [23]:
#df_datos2= pd.read_excel("c:/datos/1434628.xlsx", sheet_name=0, dtype=str)
df_datos2= pd.read_excel("c:/datos/1434628.xlsx", sheet_name=0)
df_datos2.columns = (df_datos2.columns.str.strip().str.upper().str.replace(r'[^A-Za-z0-9]', '_', regex=True))

In [25]:
df_datos2.info()

<class 'pandas.DataFrame'>
RangeIndex: 3343 entries, 0 to 3342
Data columns (total 42 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   IDEPOL                    3096 non-null   float64
 1   CERT_BANCO_EXCEL          3343 non-null   int64
 2   NRO_CERT_BANCO            3096 non-null   str
 3   TIPO_SEGURO               0 non-null      float64
 4   CODPROD                   3096 non-null   float64
 5   NUMPOL                    3096 non-null   float64
 6   CLIENTE                   3096 non-null   str
 7   NUMCERT                   3096 non-null   float64
 8   STSCERT                   3096 non-null   str
 9   FEC_INI_VIG_CERT          3096 non-null   datetime64[us]
 10  FEC_FIN_VIG_CERT          3096 non-null   datetime64[us]
 11  FECHA_INI_ULT_COBERTURA   3096 non-null   datetime64[us]
 12  FECHA_FIN_ULT_COBERTURA   3096 non-null   datetime64[us]
 13  CAN_LQ_COB                3343 non-null   int64
 14  CAN_LQ_INC                3343 non-null   int64
 15  CAN_LQ_ANU                3343 non-null   int64
 16  CAN_LQ_EMI                3343 non-null   int64
 17  DOCUMENTO_COB             2479 non-null   float64
 18  DOCUMENTO_ESTADO_COB      2479 non-null   str
 19  PRIMA_COB                 2479 non-null   float64
 20  FECVE_COB                 2479 non-null   datetime64[us]
 21  DOCUMENTO_ANU_INC         688 non-null    float64
 22  DOCUMENTO_ESTADO_ANU_INC  688 non-null    str
 23  PRIMA_INC_ANU             688 non-null    float64
 24  FECVE_COB_1               688 non-null    datetime64[us]
 25  P_BRUTA                   3085 non-null   float64
 26  TIPODOC                   1165 non-null   str
 27  NUMERO_LA                 1165 non-null   float64
 28  MTO_LA                    1165 non-null   float64
 29  ESTADO_LA                 1165 non-null   str
 30  CAN_LA_EMI                3343 non-null   int64
 31  NUMSIN                    133 non-null    float64
 32  STSSIN                    133 non-null    str
 33  FECOCURR                  133 non-null    datetime64[us]
 34  MTOTOTRES                 133 non-null    float64
 35  MTOTOTAPROB               133 non-null    float64
 36  MTOTOTPAGADO              133 non-null    float64
 37  MTOTOTPEND                133 non-null    float64
 38  DESCRAMO                  133 non-null    str
 39  TIPOVIG                   3343 non-null   str
 40  CODMONEDA                 3096 non-null   str
 41  CALCULO_PRIMA             3343 non-null   str
dtypes: datetime64[us](7), float64(17), int64(6), str(12)
memory usage: 1.1 MB

In [9]:
df_datos= df_datos.rename(columns={'NRO_CERT_BANCO':'CERTIFICADO_BANCO', 'TIPO_SEGURO':'PRODUCTO',
                                'FEC_INI_VIG_CERT':'FECHA_INICIO_VIGENCIA', 'FEC_FIN_VIG_CERT':'FECHA_FIN_VIGENCIA',
                                'FECVE_COB':'FECHA_VE_COB', 'FECVE_COB_1':'FECHA_VE_INCANU','FECOCURR':'FECHA_OCURR',
                                'DOCUMENTO_COB':'DOC_COB', 'DOCUMENTO_ESTADO_COB':'DOC_ESTADO_COB',
                                'DOCUMENTO_ANU_INC':'DOC_ANU_INC','DOCUMENTO_ESTADO_ANU_INC':'DOC_ESTADO_ANU_INC',
                                'P_BRUTA':'PRIMA_BRUTA','MTO_LA':'MONTO_LA'})

In [ ]:
df_datos['FECHA_INICIO_VIGENCIA'] = pd.to_datetime(df_datos['FECHA_INICIO_VIGENCIA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_FIN_VIGENCIA'] = pd.to_datetime(df_datos['FECHA_FIN_VIGENCIA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_INI_ULT_COBERTURA'] = pd.to_datetime(df_datos['FECHA_INI_ULT_COBERTURA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_FIN_ULT_COBERTURA'] = pd.to_datetime(df_datos['FECHA_FIN_ULT_COBERTURA'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_VE_COB'] = pd.to_datetime(df_datos['FECHA_VE_COB'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_VE_INCANU'] = pd.to_datetime(df_datos['FECHA_VE_INCANU'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['FECHA_OCURR'] = pd.to_datetime(df_datos['FECHA_OCURR'],format='%Y-%m-%d %H:%M:%S', errors='coerce').dt.date
df_datos['CAN_LQ_COB'] = pd.to_numeric(df_datos['CAN_LQ_COB'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_INC'] = pd.to_numeric(df_datos['CAN_LQ_INC'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_ANU'] = pd.to_numeric(df_datos['CAN_LQ_ANU'], errors='coerce').astype('Int64')
df_datos['CAN_LQ_EMI'] = pd.to_numeric(df_datos['CAN_LQ_EMI'], errors='coerce').astype('Int64')
df_datos['PRIMA_COB'] = pd.to_numeric(df_datos['PRIMA_COB'], errors="coerce").astype('float64')
df_datos['PRIMA_INC_ANU'] = pd.to_numeric(df_datos['PRIMA_INC_ANU'], errors="coerce").astype('float64')
df_datos['PRIMA_BRUTA'] = pd.to_numeric(df_datos['PRIMA_BRUTA'], errors="coerce").astype('float64')
df_datos['MONTO_LA'] = pd.to_numeric(df_datos['MONTO_LA'], errors="coerce").astype('float64')
df_datos['MTOTOTRES'] = pd.to_numeric(df_datos['MTOTOTRES'], errors="coerce").astype('float64')
df_datos['MTOTOTAPROB'] = pd.to_numeric(df_datos['MTOTOTAPROB'], errors="coerce").astype('float64')
df_datos['MTOTOTPAGADO'] = pd.to_numeric(df_datos['MTOTOTPAGADO'], errors="coerce").astype('float64')
df_datos['MTOTOTPEND'] = pd.to_numeric(df_datos['MTOTOTPEND'], errors="coerce").astype('float64')

df_datos['FECHA_INI_ULT_COBERTURA'] = df_datos.apply(lambda r: restar_fecha(r['FECHA_FIN_ULT_COBERTURA'], r['CALCULO_PRIMA']), axis=1)

In [11]:
df_datos.head(3)

,IDEPOL,CERT_BANCO_EXCEL,CERTIFICADO_BANCO,CODPROD,NUMPOL,CLIENTE,NUMCERT,STSCERT,FECHA_INICIO_VIGENCIA,FECHA_FIN_VIGENCIA,FECHA_INI_ULT_COBERTURA,FECHA_FIN_ULT_COBERTURA,CAN_LQ_COB,CAN_LQ_INC,CAN_LQ_ANU,CAN_LQ_EMI,DOC_COB,DOC_ESTADO_COB,PRIMA_COB,FECHA_VE_COB,DOC_ANU_INC,DOC_ESTADO_ANU_INC,PRIMA_INC_ANU,FECHA_VE_INCANU,PRIMA_BRUTA,TIPODOC,NUMERO_LA,MONTO_LA,ESTADO_LA,CAN_LA_EMI,NUMSIN,STSSIN,FECHA_OCURR,MTOTOTRES,MTOTOTAPROB,MTOTOTPAGADO,MTOTOTPEND,DESCRAMO,TIPOVIG,CODMONEDA,CALCULO_PRIMA
0,12566562,00119999594000271325,00119999594000271325,1103,500093,VILMA JIMENEZ JIMENEZ,109846,ANU,4/10/2021,22/05/2065,16/10/2024,4/10/2025,4,0,0,4,904952527,COB,41,25/11/2021,NaN,NaN,NaN,NaN,33.73,LA,176259245,39.98,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL
1,12566562,00119999584000249052,00119999584000249052,1103,500093,OSCAR CIEZA HEREDIA,109838,ANU,6/05/2021,31/01/2057,29/11/2025,6/05/2026,5,0,0,5,904951030,COB,41,25/11/2021,NaN,NaN,NaN,NaN,33.73,LA,178358985,17.81,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL
2,11995329,00119999574000267980,00119999574000267980,1103,500091,RAFAEL DIAZ JULIAN,9981,ANU,3/09/2020,1/06/2040,6/05/2026,3/09/2026,6,0,0,6,825590690,COB,41,10/11/2020,NaN,NaN,NaN,NaN,33.73,LA,179637360,13.56,ACT,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,L-LIBRE,USD,A-ANUAL

In [15]:
df_datos2.tail(3)

,IDEPOL,CERT_BANCO_EXCEL,NRO_CERT_BANCO,TIPO_SEGURO,CODPROD,NUMPOL,CLIENTE,NUMCERT,STSCERT,FEC_INI_VIG_CERT,FEC_FIN_VIG_CERT,FECHA_INI_ULT_COBERTURA,FECHA_FIN_ULT_COBERTURA,CAN_LQ_COB,CAN_LQ_INC,CAN_LQ_ANU,CAN_LQ_EMI,DOCUMENTO_COB,DOCUMENTO_ESTADO_COB,PRIMA_COB,FECVE_COB,DOCUMENTO_ANU_INC,DOCUMENTO_ESTADO_ANU_INC,PRIMA_INC_ANU,FECVE_COB_1,P_BRUTA,TIPODOC,NUMERO_LA,MTO_LA,ESTADO_LA,CAN_LA_EMI,NUMSIN,STSSIN,FECOCURR,MTOTOTRES,MTOTOTAPROB,MTOTOTPAGADO,MTOTOTPEND,DESCRAMO,TIPOVIG,CODMONEDA,CALCULO_PRIMA
3340,1628856091,00110163334000433929,00110163334000433929,NaN,1121,256392,ERNESTO FLORES VENTURA,1,ANU,2025-03-15 00:00:00,2026-03-15 00:00:00,2026-01-21 00:00:00,2026-03-15 00:00:00,1,0,0,1,1163634749,COB,179.01,2025-03-15 00:00:00,NaN,NaN,NaN,NaN,147.28,LA,179407314,25.92,PAG,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL
3341,1628858647,00110348024000531497,00110348024000531497,NaN,1121,107391,PAUL DAVE ROMERO CANARIO,1,REN,2025-04-30 00:00:00,2026-04-30 00:00:00,2025-04-30 00:00:00,2026-04-30 00:00:00,1,0,0,1,1163644968,COB,179.89,2025-04-30 00:00:00,NaN,NaN,NaN,NaN,148.01,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL
3342,1628494378,00110659014000253250,00110659014000253250,NaN,1121,72335,MABEL LIDANA MAGUIÑA DIAZ,1,REN,2025-02-12 00:00:00,2026-02-12 00:00:00,2025-02-12 00:00:00,2026-02-12 00:00:00,1,0,0,1,1161485876,COB,179.89,2025-02-12 00:00:00,NaN,NaN,NaN,NaN,148.01,NaN,NaN,NaN,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,A-ANUAL,SOL,A-ANUAL

In [12]:
df_datos.info()

<class 'pandas.DataFrame'>
RangeIndex: 265657 entries, 0 to 265656
Data columns (total 41 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   IDEPOL                   96455 non-null   str
 1   CERT_BANCO_EXCEL         265657 non-null  str
 2   CERTIFICADO_BANCO        96455 non-null   str
 3   CODPROD                  96455 non-null   str
 4   NUMPOL                   96455 non-null   str
 5   CLIENTE                  96455 non-null   str
 6   NUMCERT                  96455 non-null   str
 7   STSCERT                  96455 non-null   str
 8   FECHA_INICIO_VIGENCIA    96450 non-null   str
 9   FECHA_FIN_VIGENCIA       96449 non-null   str
 10  FECHA_INI_ULT_COBERTURA  96454 non-null   str
 11  FECHA_FIN_ULT_COBERTURA  96454 non-null   str
 12  CAN_LQ_COB               265657 non-null  str
 13  CAN_LQ_INC               265657 non-null  str
 14  CAN_LQ_ANU               265657 non-null  str
 15  CAN_LQ_EMI               265657 non-null  str
 16  DOC_COB                  90596 non-null   str
 17  DOC_ESTADO_COB           90596 non-null   str
 18  PRIMA_COB                90596 non-null   str
 19  FECHA_VE_COB             90596 non-null   str
 20  DOC_ANU_INC              8870 non-null    str
 21  DOC_ESTADO_ANU_INC       8870 non-null    str
 22  PRIMA_INC_ANU            8870 non-null    str
 23  FECHA_VE_INCANU          8870 non-null    str
 24  PRIMA_BRUTA              96216 non-null   str
 25  TIPODOC                  74804 non-null   str
 26  NUMERO_LA                74804 non-null   str
 27  MONTO_LA                 74804 non-null   str
 28  ESTADO_LA                74804 non-null   str
 29  CAN_LA_EMI               265657 non-null  str
 30  NUMSIN                   2789 non-null    str
 31  STSSIN                   2789 non-null    str
 32  FECHA_OCURR              2789 non-null    str
 33  MTOTOTRES                2789 non-null    str
 34  MTOTOTAPROB              2789 non-null    str
 35  MTOTOTPAGADO             2789 non-null    str
 36  MTOTOTPEND               2789 non-null    str
 37  DESCRAMO                 2789 non-null    str
 38  TIPOVIG                  265657 non-null  str
 39  CODMONEDA                96455 non-null   str
 40  CALCULO_PRIMA            265657 non-null  str
dtypes: str(41)
memory usage: 83.1 MB